#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory
#------------------------------------------------------------------------------

wclean libso DPMTurbulenceModels

wclean
wclean MPPICFoamEx
wclean DPMDyMFoamEx
wclean DPMDyMFoamEx/MPPICDyMFoamEx

#------------------------------------------------------------------------------
